### ISSUE TITLE
Lol, seriously?

### ISSUE THREAD

**Issue by Streiw** [d-jahren/extract-mfg#3]
"this method was popularized by streiw although I independently discovered & verified the bug. I'll post a more detailed write up later."  

You didnt discover this bug or method, Dan. You got the information from my pastebin instructions that I posted 3 days before you created this repository. Why do you feel the need to lie about this? It'll be really cute to see your "write up" about this considering you got the information from me.  Keep it classy, bud.

**Comment by d-jahren** [comment]
It was the truth but since you're being so awfully rude, I'll just remove it...
